# Lung CT Processing Pipeline Configuration

# Data paths
data:
  root_dir: "data/Case1Pack"
  output_dir: "data_processed"
  
# Phases to process
phases:
  reference_phase: "T00"
  target_phases: ["T10", "T20", "T30", "T40", "T50", "T60", "T70", "T80", "T90"]
  all_phases: ["T00", "T10", "T20", "T30", "T40", "T50", "T60", "T70", "T80", "T90"]

# Case information
case:
  case_id: 1
  case_name: "Case1Pack"

# Segmentation parameters
segmentation:
  use_totalsegmentator: true
  roi_subset: ["lung_left", "lung_right"]
  create_combined_mask: true
  mask_threshold: 0.5
  
  # Fallback parameters if TotalSegmentator not available
  fallback:
    hu_min: -1000
    hu_max: -200
    morphological_operations: true
    closing_radius: 2
    opening_radius: 1

# Mesh extraction parameters
mesh:
  marching_cubes:
    level: 0.5
    step_size: 1
    use_smoothing: true
    smoothing_iterations: 5
  
  quality_control:
    min_triangle_area: 1e-10
    max_edge_length: 10.0
    min_edge_length: 0.1
    
  remeshing:
    enabled: false
    target_edge_length: 2.0
    
  output_formats: ["xdmf", "vtk"]

# Deformation field parameters
deformation:
  interpolation_method: "cubic"
  extrapolation_value: 0.0
  coordinate_system: "physical"  # or "voxel"
  
  quality_checks:
    max_displacement: 50.0  # mm
    check_jacobian: true
    min_jacobian: 0.1
    max_jacobian: 10.0

# Batch processing parameters
batch:
  process_all_pairs: true
  parallel_processing: false
  max_workers: 4
  
  # Specific phase pairs to process (if process_all_pairs is false)
  specific_pairs:
    - ["T00", "T10"]
    - ["T00", "T20"]
    - ["T00", "T50"]

# Validation parameters
validation:
  check_mesh_quality: true
  check_displacement_magnitude: true
  save_quality_reports: true
  
  thresholds:
    max_displacement_magnitude: 30.0  # mm
    min_mesh_volume: 1000.0  # mm³
    max_mesh_volume: 10000000.0  # mm³

# Output parameters
output:
  save_intermediate_results: true
  save_quality_metrics: true
  save_visualization: false
  
  file_naming:
    mesh_template: "case{case_id}_{phase}_lung_regions_{version}.{ext}"
    warped_template: "case{case_id}_{from_phase}_to_{to_phase}_warped.{ext}"
    quality_template: "case{case_id}_{phase}_quality_report.json"

# Logging parameters
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  save_to_file: true
  log_file: "pipeline.log"
  
# Dependencies and optional features
dependencies:
  required:
    - "numpy"
    - "nibabel"
    - "meshio"
    - "scipy"
    - "scikit-image"
  
  optional:
    - "totalsegmentator"
    - "pymeshlab"
    - "fenics"
    - "dolfin"
    
  fallback_behavior:
    totalsegmentator_missing: "use_threshold_segmentation"
    pymeshlab_missing: "skip_remeshing"
    fenics_missing: "use_meshio_only"